name: Updates e2e basic EAS

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - .github/workflows/updates-e2e.yml
      - packages/expo-json-utils/**
      - packages/expo-manifests/**
      - packages/expo-modules-core/**
      - packages/expo-structured-headers/**
      - packages/expo-updates-interface/**
      - packages/expo-updates/**
      - packages/expo/android/**
      - packages/expo/ios/**
      - templates/expo-template-bare-minimum/**
  push:
    branches: [main, 'sdk-*']
    paths:
      - .github/workflows/updates-e2e.yml
      - packages/expo-json-utils/**
      - packages/expo-manifests/**
      - packages/expo-modules-core/**
      - packages/expo-structured-headers/**
      - packages/expo-updates-interface/**
      - packages/expo-updates/**
      - packages/expo/android/**
      - packages/expo/ios/**
      - templates/expo-template-bare-minimum/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    env:
      UPDATES_PORT: 4747
    strategy:
      matrix:
        api-level: [31]
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v3
      - name: ⬢ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: ➕ Add `bin` to GITHUB_PATH
        run: echo "$(yarn global bin)" >> $GITHUB_PATH
      - name: ♻️ Restore caches
        uses: ./.github/actions/expo-caches
        id: expo-caches
        with:
          yarn-workspace: 'true'
          avd: 'true'
          avd-api: ${{ matrix.api-level }}
          react-native-gradle-downloads: 'true'
      - name: 🧶 Yarn install
        if: steps.expo-caches.outputs.yarn-workspace-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: 🛠 Build local Expo CLI
        working-directory: packages/@expo/cli
        run: yarn prepare
      - name: Build expo-updates CLI
        working-directory: packages/expo-updates
        run: yarn build:cli
      - name: 🔧 Install Expo CLI
        run: yarn global add expo-cli
      - name: 🌳 Add EXPO_REPO_ROOT to environment
        run: echo "EXPO_REPO_ROOT=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: 🌐 Set updates host
        run: echo "UPDATES_HOST=localhost" >> $GITHUB_ENV
      - name: 🌐 Set updates port
        run: echo "UPDATES_PORT=4747" >> $GITHUB_ENV
      - name: 📦 Get artifacts path
        run: mkdir -p artifact && echo "ARTIFACTS_DEST=$(pwd)/artifact" >> $GITHUB_ENV
      - name: 📦 Get commit message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B | head -c1000)" >> $GITHUB_ENV
      - name: 📦 Set test project location
        run: echo "TEST_PROJECT_ROOT=$GITHUB_WORKSPACE/updates-e2e" >> $GITHUB_ENV
      - name: 📦 Setup test project

        run: node packages/expo-updates/e2e/__tests__/setup/create-eas-project.js
      - name: 🚀 Build with EAS
        uses: ./.github/actions/eas-build
        id: build
        with:
          platform: 'android'
          profile: 'updates_testing'
          projectRoot: './updates-e2e'
          expoToken: ${{ secrets.EAS_BUILD_BOT_TOKEN }}
          resourceClass: large
          noWait: ${{ github.event.schedule }}
          message: ${{ github.event.pull_request.title }}
      - name: On workflow canceled
        if: ${{ cancelled() && steps.build.outputs.build_id }}
        run: eas build:cancel ${{ steps.build.outputs.build_id }}
        working-directory: ./apps/eas-expo-go
        env:
          EXPO_TOKEN: ${{ secrets.EAS_BUILD_BOT_TOKEN }}
          EAS_BUILD_PROFILE: ${{ steps.profile.outputs.profile  }}
